---
title: "Pre_Supplementary_Figure1.Rmd"
author: "Michael Noe"
date: "`r Sys.Date()`" 
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---


## Prerequisites:

These packages are necessary to process the data to make these figures

```{r packages, echo=FALSE}
library("tidyverse")
library("here")
```


```{r}
outdir <- here("output", "Pre_Supplementary_Figure1.Rmd")
dir.create(outdir)
dir.create(here(outdir, "motifs_cfdna_144_167"))
```


## Process the data

  *code/motifs_cfdna_144_167.sh* -> outputs "motifs_cfdna_144_167"
    Gets nucleotide distributions over both 144bp cfDNA fragments and 167bp cfDNA fragments

## Get information on nucleotide frequencies in 144bp and 167bp reads

```{r}
loc <- here(outdir, "motifs_cfdna_144_167")
ls <- list.files(loc)

t <- tibble()
for (file in ls) {
  print(paste0(match(file, ls), " / ", length(ls)))
  temp <- readRDS(file.path(loc, file))
  if (nrow(temp) != 0) {
    if (ncol(t) != 0) {
      temp <- temp[, match(colnames(t), colnames(temp))]
    }
    t <- rbind(t, temp)
    if (length(grep("N", t$Var1)) != 0) {
      t <- t[-grep("N", t$Var1), ]
    }
    t <- t %>%
      group_by(Var1, pos, group, motif_length) %>%
      summarise(Freq = sum(Freq))
    t <- ungroup(t[, c(1, 5, 2, 4, 3)])
    print(t[1, 2])
  }
}

saveRDS(t, here("data/motifs_cfdna_144_167.rds"))
```
