---
title: "Supplementary_Figure4.Rmd"
author: "Michael Noe"
date: "`r Sys.Date()`" 
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---


## Pre-requisites

These packages are necessary to make the plots that make up Supplementary Figure 4.

```{r}
library("tidyverse")
library("cowplot")
library("here")
```

## Supplementary Figure 4: an updated version of Figure 2b and 2c based on Loyfer data

```{r}
t <- readRDS(here("data/Loyfer_50_ratios.rds"))
t[which(nchar(t$seq) == 3),]$seq <- paste0(substr(t[which(nchar(t$seq) == 3),]$seq, 1, 1), " | ", substr(t[which(nchar(t$seq) == 3),]$seq, 2, 3))
t[which(nchar(t$seq) == 4),]$seq <- paste0(substr(t[which(nchar(t$seq) == 4),]$seq, 1, 1), " | ", substr(t[which(nchar(t$seq) == 4),]$seq, 2, 4))
t$seq <- factor(t$seq, levels = c("C | CG", "G | CG", "A | CG", "T | CG",
                                  "C | CCG", "G | CCG", "A | CCG", "T | CCG"))
#t$beta <- round(t$beta, digits = 1)
t <- t %>%
  group_by(seq, beta) %>%
  summarise(start = sum(start), over = sum(over))
t$ratio <- t$start / t$over
t_add <- t %>%
  group_by(seq) %>%
  summarise(beta = 1, start = 0, over = 1, ratio = 0)
t <- rbind(t, t_add)
plot2b <- ggplot(t[which(nchar(as.character(t$seq)) == 6),], aes(x=factor(beta), y=ratio, fill=beta)) +
  geom_bar(stat="identity", position = "dodge") +
  facet_wrap(~seq, nrow=1) +
  theme_classic(base_size = 20) +
  #xlab("Methylation (beta-value)") +
  #ylab(expression(atop("Fraction of cfDNA fragments", paste("starting or ending at CGs")))) +
  ylab("Fraction of cfDNA fragments\nstarting or ending at CGs") + 
  scale_y_continuous(labels = scales::percent, limits = c(0,0.0075),
                     breaks = c(0.0075,0.005,0.0025,0)) +
  scale_x_discrete(labels=c("0", "1"),
                   breaks = c(0, 1)) +
  theme(text = element_text(size=16),
        axis.text.x = element_text(angle = 0, hjust=0.5),
        #axis.text.x = element_blank(),
        #axis.title.y = element_text(margin = margin(r = 5)),
        axis.title.x = element_blank(),
        strip.background=element_rect(color = NA),
        panel.spacing=unit(2, "lines"),
        strip.placement = "outside",
        legend.position = "none",
        axis.title.y = element_text(margin = margin(r = 20, l = 20))) +
  scale_fill_gradient(low="#77C8DD", high="#004766")

plot2c <- ggplot(t[which(nchar(as.character(t$seq)) == 7),], aes(x=factor(beta), y=ratio, fill=beta)) +
  geom_bar(stat="identity", position = "dodge") +
  facet_wrap(~seq, nrow=1) +
  theme_classic(base_size = 20) +
  #xlab("Methylation (beta-value)") +
  #ylab(expression(atop("Fraction of cfDNA fragments", paste("starting or ending at CGs")))) +
  ylab("Fraction of cfDNA fragments\nstarting or ending at CGs") + 
  scale_y_continuous(labels = scales::percent, limits = c(0,0.008),
                     breaks = c(0.0075,0.005,0.0025,0)) +
  scale_x_discrete(labels=c("0", "1"),
                   breaks = c(0,1)) +
  theme(text = element_text(size=16),
        axis.text.x = element_text(angle = 0, hjust=0.5),
        #axis.text.x = element_blank(),
        #axis.title.y = element_text(margin = margin(r = 5)),
        axis.title.x = element_blank(),
        strip.background=element_rect(color = NA),
        panel.spacing=unit(2, "lines"),
        strip.placement = "outside",
        legend.position = "none",
        axis.title.y = element_text(margin = margin(r = 20, l = 20))) +
  scale_fill_gradient(low="#77C8DD", high="#004766")

#title <- textGrob("window: +/- 50 bps (total: 101 bps)", gp = gpar(col = "black", fontsize = 19))
plot2bc_50 <- plot_grid(plot2b, plot2c, ncol = 1, align="v", axis="bt", rel_heights = c(5, 5), labels = c("a", "b"), label_size = 20)
#plot2BC <- plot_grid(plot2b, plot2c, ncol = 1, align="v", axis="bt", rel_heights = c(5, 5), labels = c("b", "c"), label_size = 20)
ggsave(here("docs/figure/Supplementary_Fig_4.jpg"), plot = plot2bc_50, device = "jpeg",width = 20, height=12,units = "in", dpi=300)
```

```{r}

t %>%
    group_by(seq) %>%
    summarize(min = min(ratio[ratio > 0]), max = max(ratio), ratio = max(ratio)/min(ratio[ratio > 0]))

```

