---
title: "Supplementary_Figure2.Rmd"
author: "Michael Noe"
date: "2024-01-26"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

## Pre-requisites

These packages are necessary to make the plots that make up Supplementary Figure 2.

```{r}
library("tidyverse")
library("here")
```


## Supplementary Figure 2: 

```{r}
t <- readRDS(here("data", "position_in_read.rds"))
t_normalizer <- unique(t[,c(5,6)])
t_normalizer$normal <- t_normalizer$somatic_all / mean(t_normalizer$somatic_all)
t$normal <- t_normalizer[match(t$case, t_normalizer$case),]$normal
t$n <- t$n / t$normal
t_b_small <- tibble()
for (i in c(0.1, 0.2, 0.3, 0.4, 0.5)) {
  t_b_small_temp <- t[which(t$beta <= i),] %>% 
    group_by(diff, case, motif) %>%
    summarise(n = sum(n))
  t_b_small_temp$beta <- i
  t_b_small <- rbind(t_b_small, t_b_small_temp)
}
#t_b_small$beta <- paste0("<= ", t_b_small$beta)
t_b_large <- tibble()
for (i in c(0.5, 0.6, 0.7, 0.8, 0.9)) {
  t_b_large_temp <- t[which(t$beta >= i),] %>% 
    group_by(diff, case, motif) %>%
    summarise(n = sum(n))
  t_b_large_temp$beta <- 1 - i
  t_b_large <- rbind(t_b_large, t_b_large_temp)
}
#t_b_large$beta <- paste0(">= ", t_b_large$beta)


t_b_small$group <- "Unmethylated"
t_b_large$group <- "Methylated"

t_b <- rbind(t_b_small, t_b_large)
t_b$beta <- factor(t_b$beta, levels = c(0.1, 0.2, 0.3, 0.4, 0.5))


for (i in unique(t_b$beta)) {
  t_b[which((t_b$beta == i) & (t_b$motif == "CG") & (t_b$group == "Unmethylated")),]$n <- t_b[which((t_b$beta == i) & (t_b$motif == "CG") & (t_b$group == "Unmethylated")),]$n * (mean(t_b[which((t_b$beta == i) & (t_b$motif == "CG") & (t_b$group == "Methylated")),]$n) / mean(t_b[which((t_b$beta == i) & (t_b$motif == "CG") & (t_b$group == "Unmethylated")),]$n))
    t_b[which((t_b$beta == i) & (t_b$motif == "CCG") & (t_b$group == "Unmethylated")),]$n <- t_b[which((t_b$beta == i) & (t_b$motif == "CCG") & (t_b$group == "Unmethylated")),]$n * (mean(t_b[which((t_b$beta == i) & (t_b$motif == "CCG") & (t_b$group == "Methylated")),]$n) / mean(t_b[which((t_b$beta == i) & (t_b$motif == "CCG") & (t_b$group == "Unmethylated")),]$n))
}

t_b.summary <- t_b %>%
  group_by(diff, beta, motif, group) %>%
  summarise(
    sd = sd(n, na.rm = TRUE),
    n = mean(n)
  )
t_b.summary$beta <- factor(t_b.summary$beta, levels = c(0.1, 0.2, 0.3, 0.4, 0.5))
t_b$group_beta <- paste0(t_b$group, "_", t_b$beta)
t_b.summary$group_beta <- paste0(t_b.summary$group, "_", t_b.summary$beta)
t_b$beta <- as.numeric(as.character(t_b$beta))
t_b$beta <- paste0("Methylated: beta >= ", 1 - t_b$beta, ";\nUnmethylated: beta <= ", t_b$beta)
t_b.summary$beta <- as.numeric(as.character(t_b.summary$beta))
t_b.summary$beta <- paste0("Methylated: beta >= ", 1 - t_b.summary$beta, ";\nUnmethylated: beta <= ", t_b.summary$beta)

plot_cg <- ggplot(t_b[which((t_b$diff >= 1) & (t_b$diff <= 40) & (t_b$motif == "CG")),], aes(x=diff, y=n, colour=group_beta, fill=group_beta)) +
  geom_point(position=position_jitter(h=0.01, w=0.4), alpha = 1, size = 0.1) +
  geom_bar(stat = "identity", data = t_b.summary[which((t_b.summary$diff>= 1) & (t_b.summary$diff <= 40) & (t_b.summary$motif == "CG")),], colour="black", alpha=0.7) +
   geom_errorbar(
    aes(ymin = n-sd, ymax = n+sd),
    data = t_b.summary[which((t_b.summary$diff>= 1) & (t_b.summary$diff <= 40) & (t_b.summary$motif == "CG")),], width = 0.2, colour="black") +
  facet_grid(rows = vars(beta),
             cols = vars(group),
             scales = "free_y",
             space = "fixed") +
  theme_classic(base_size = 20) +
  theme(text = element_text(size=16),
        axis.title.y = element_text(margin = margin(l = 20, r = 20)),
        axis.title.x = element_text(margin = margin(t = 20, b = 40)),
        strip.background=element_rect(color = NA),
        panel.spacing=unit(2, "lines"),
        strip.placement = "top",
        legend.position = "none",
        strip.text.y.right = element_text(angle = 0)) +
  scale_fill_manual(values=c("#004766", "#255672", "#3d667e", "#53768A", "#698696", "#77c8dd", "#93cfe3", "#acd7e7", "#c2deeb", "#d7e6ee")) +
  scale_colour_manual(values=c("#004766", "#255672", "#3d667e", "#53768A", "#698696", "#77c8dd", "#93cfe3", "#acd7e7", "#c2deeb", "#d7e6ee")) +
  ylab("") +
  xlab("Position in fragment")

ggsave(here("docs/figure/Supplementary_Fig_2.jpg"), plot = plot_cg, device = "jpeg",width = 20, height=12,units = "in", dpi=300)

plot_ccg <- ggplot(t_b[which((t_b$diff >= 1) & (t_b$diff <= 40) & (t_b$motif == "CCG")),], aes(x=diff, y=n, colour=group_beta, fill=group_beta)) +
  geom_point(position=position_jitter(h=0.01, w=0.4), alpha = 1, size = 0.1) +
  geom_bar(stat = "identity", data = t_b.summary[which((t_b.summary$diff>= 1) & (t_b.summary$diff <= 40) & (t_b.summary$motif == "CCG")),], colour="black", alpha=0.7) +
   geom_errorbar(
    aes(ymin = n-sd, ymax = n+sd),
    data = t_b.summary[which((t_b.summary$diff>= 1) & (t_b.summary$diff <= 40) & (t_b.summary$motif == "CCG")),], width = 0.2, colour="black") +
  facet_grid(rows = vars(beta),
             cols = vars(group),
             scales = "free_y",
             space = "fixed") +
  theme_classic(base_size = 20) +
  theme(text = element_text(size=16),
        axis.title.y = element_text(margin = margin(l = 20, r = 20)),
        axis.title.x = element_text(margin = margin(t = 20, b = 40)),
        strip.background=element_rect(color = NA),
        panel.spacing=unit(2, "lines"),
        strip.placement = "top",
        legend.position = "none",
        strip.text.y.right = element_text(angle = 0)) +
  scale_fill_manual(values=c("#004766", "#255672", "#3d667e", "#53768A", "#698696", "#77c8dd", "#93cfe3", "#acd7e7", "#c2deeb", "#d7e6ee")) +
  scale_colour_manual(values=c("#004766", "#255672", "#3d667e", "#53768A", "#698696", "#77c8dd", "#93cfe3", "#acd7e7", "#c2deeb", "#d7e6ee")) +
  ylab("") +
  xlab("Position in fragment")

ggsave(here("docs/figure/Supplementary_Fig_2_NOTINCLUDED_CCG.jpg"), plot = plot_ccg, device = "jpeg",width = 20, height=12,units = "in", dpi=300)
```
